name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Revision
        uses: actions/checkout@v2

      - name: Install APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: nodejs gnome-shell-extensions

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: npm

      - name: Install Node Packages
        run: npm ci

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
